// <auto-generated />
namespace TentamenAvanceradNET_AntonAsplund.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _22_43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22_43));
        
        string IMigrationMetadata.Id
        {
            get { return "202004022043327_22_43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
