// <auto-generated />
namespace TentamenAvanceradNET_AntonAsplund.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _03_07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03_07));
        
        string IMigrationMetadata.Id
        {
            get { return "202004040108078_03_07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
